import React, { useState, useContext, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  Loader2,
  CheckCircle2,
  XCircle,
  BarChart3,
  RefreshCw,
  Sparkles,
  AlertCircle,
  Trophy,
} from "lucide-react";
import { useTheme } from "../context/ThemeContext";
import { ReaderContext } from "../context/ReaderContext";

// ─── OpenAI config ─────────────────────────────────────────────────────────────
// Replace with your real key. In production, proxy this through your backend.
const OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE";
const OPENAI_MODEL = "gpt-4o-mini";

const SYSTEM_PROMPT = `You are an expert academic assessment designer. Given a passage of text, 
generate a multiple-choice comprehension quiz. Return ONLY a valid JSON array with no markdown, 
no preamble, and no trailing text. Each object must have exactly these fields:
{
  "id": number,
  "question": string,
  "options": [string, string, string, string],
  "correctIndex": number (0–3),
  "explanation": string
}
Generate exactly 5 questions. Vary difficulty from recall to inference.`;

async function generateQuiz(text) {
  const trimmed = text.slice(0, 3000);

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      temperature: 0.4,
      max_tokens: 1500,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: `Generate a 5-question multiple-choice quiz based on this text:\n\n${trimmed}`,
        },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status}`);
  }

  const data = await response.json();
  const raw = data.choices?.[0]?.message?.content || "";

  // Strip any accidental markdown fences
  const cleaned = raw.replace(/```json|```/gi, "").trim();
  return JSON.parse(cleaned);
}

// ─── Fallback quiz (when API key is placeholder or call fails) ────────────────
const FALLBACK_QUIZ = [
  {
    id: 1,
    question: "What is the primary limitation of working memory according to cognitive load theory?",
    options: [
      "It is too slow to process information",
      "It has a strictly limited capacity",
      "It cannot store visual information",
      "It decays within seconds",
    ],
    correctIndex: 1,
    explanation:
      "Sweller's theory holds that working memory has a strictly limited capacity — when overwhelmed, learning fails.",
  },
  {
    id: 2,
    question: "Which type of cognitive load is generated by poor instructional design?",
    options: ["Intrinsic load", "Germane load", "Extraneous load", "Schema load"],
    correctIndex: 2,
    explanation:
      "Extraneous load is imposed by the design of instructional materials and does not contribute to learning.",
  },
  {
    id: 3,
    question: "What are schemas in the context of cognitive load theory?",
    options: [
      "Visual diagrams used for learning",
      "Steps in a reading comprehension process",
      "Organised knowledge structures in long-term memory",
      "Mental shortcuts for decision-making",
    ],
    correctIndex: 2,
    explanation:
      "Schemas are organised knowledge structures stored in long-term memory, built through germane cognitive load.",
  },
  {
    id: 4,
    question: "What does the expertise reversal effect describe?",
    options: [
      "Experts performing worse under stress",
      "Techniques effective for novices becoming counterproductive for experts",
      "Beginners outperforming experts on recall tasks",
      "The reversal of learning gains after sleep",
    ],
    correctIndex: 1,
    explanation:
      "The expertise reversal effect is one of the empirically validated principles of cognitive load theory.",
  },
  {
    id: 5,
    question: "What is the primary goal of effective instructional design according to the passage?",
    options: [
      "Maximise the amount of information presented per hour",
      "Eliminate all forms of cognitive load",
      "Reduce extraneous load and redirect resources toward germane processing",
      "Replace working memory with long-term memory strategies",
    ],
    correctIndex: 2,
    explanation:
      "The passage states that effective design reduces extraneous load and frees cognitive resources for germane processing.",
  },
];

// ─── Option button ────────────────────────────────────────────────────────────
function OptionButton({ label, index, selected, correct, revealed, onSelect, styles }) {
  let bg = "var(--color-surface)";
  let border = "var(--color-border)";
  let color = "var(--color-text)";
  let icon = null;

  if (revealed) {
    if (index === correct) {
      bg = "#22c55e18";
      border = "#22c55e88";
      color = "#16a34a";
      icon = <CheckCircle2 size={15} color="#22c55e" />;
    } else if (index === selected && index !== correct) {
      bg = "#ef444418";
      border = "#ef444488";
      color = "#dc2626";
      icon = <XCircle size={15} color="#ef4444" />;
    }
  } else if (index === selected) {
    bg = `${styles.accent}18`;
    border = `${styles.accent}88`;
    color = styles.accent;
  }

  return (
    <button
      onClick={() => !revealed && onSelect(index)}
      disabled={revealed}
      style={{
        display: "flex",
        alignItems: "center",
        gap: "12px",
        width: "100%",
        padding: "13px 16px",
        borderRadius: "10px",
        border: `1.5px solid ${border}`,
        background: bg,
        color,
        cursor: revealed ? "default" : "pointer",
        fontSize: "14px",
        fontWeight: index === selected || (revealed && index === correct) ? "600" : "400",
        textAlign: "left",
        transition: "all 0.2s ease",
        lineHeight: "1.5",
      }}
    >
      <span
        style={{
          width: 24,
          height: 24,
          borderRadius: "50%",
          border: `1.5px solid ${border}`,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "11px",
          fontWeight: "700",
          flexShrink: 0,
          background: index === selected && !revealed ? styles.accent : "transparent",
          color: index === selected && !revealed ? "#fff" : "inherit",
        }}
      >
        {icon || ["A", "B", "C", "D"][index]}
      </span>
      {label}
    </button>
  );
}

// ─── Quiz card ────────────────────────────────────────────────────────────────
function QuizCard({ question, qIndex, total, answer, onAnswer, onNext, isLast, styles }) {
  const revealed = answer !== undefined && answer !== null;
  const isCorrect = revealed && answer === question.correctIndex;

  return (
    <div
      style={{
        background: "var(--color-surface)",
        border: "1px solid var(--color-border)",
        borderRadius: "16px",
        padding: "28px 28px 24px",
        display: "flex",
        flexDirection: "column",
        gap: "20px",
        animation: "cardIn 0.35s ease forwards",
      }}
    >
      {/* Progress chip */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <span
          style={{
            fontSize: "11px",
            fontWeight: "700",
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            color: styles.accent,
          }}
        >
          Question {qIndex + 1} of {total}
        </span>
        <div
          style={{
            display: "flex",
            gap: "4px",
          }}
        >
          {Array.from({ length: total }).map((_, i) => (
            <div
              key={i}
              style={{
                width: 20,
                height: 4,
                borderRadius: "2px",
                background:
                  i < qIndex
                    ? styles.accent
                    : i === qIndex
                    ? `${styles.accent}66`
                    : "var(--color-border)",
                transition: "background 0.3s",
              }}
            />
          ))}
        </div>
      </div>

      {/* Question */}
      <p
        style={{
          fontSize: "17px",
          fontWeight: "600",
          color: "var(--color-text)",
          lineHeight: "1.55",
          letterSpacing: "-0.01em",
        }}
      >
        {question.question}
      </p>

      {/* Options */}
      <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
        {question.options.map((opt, i) => (
          <OptionButton
            key={i}
            label={opt}
            index={i}
            selected={answer}
            correct={question.correctIndex}
            revealed={revealed}
            onSelect={onAnswer}
            styles={styles}
          />
        ))}
      </div>

      {/* Explanation */}
      {revealed && (
        <div
          style={{
            padding: "12px 14px",
            borderRadius: "10px",
            background: isCorrect ? "#22c55e0e" : "#ef44440e",
            border: `1px solid ${isCorrect ? "#22c55e33" : "#ef444433"}`,
            animation: "fadeIn 0.3s ease",
          }}
        >
          <p
            style={{
              fontSize: "13px",
              color: isCorrect ? "#16a34a" : "#dc2626",
              fontWeight: "600",
              marginBottom: "4px",
            }}
          >
            {isCorrect ? "✓ Correct!" : "✗ Incorrect"}
          </p>
          <p
            style={{
              fontSize: "13px",
              color: "var(--color-text)",
              lineHeight: "1.55",
            }}
          >
            {question.explanation}
          </p>
        </div>
      )}

      {/* Next button */}
      {revealed && (
        <button
          onClick={onNext}
          style={{
            alignSelf: "flex-end",
            display: "flex",
            alignItems: "center",
            gap: "8px",
            padding: "11px 22px",
            borderRadius: "10px",
            border: "none",
            background: styles.accent,
            color: "#fff",
            cursor: "pointer",
            fontSize: "14px",
            fontWeight: "600",
            boxShadow: `0 3px 12px ${styles.accent}44`,
            animation: "fadeIn 0.3s ease",
          }}
        >
          {isLast ? (
            <>
              <Trophy size={15} />
              See Results
            </>
          ) : (
            <>Next Question</>
          )}
        </button>
      )}
    </div>
  );
}

// ─── Results screen ───────────────────────────────────────────────────────────
function ResultsScreen({ questions, answers, onRetry, onViewStats, styles }) {
  const score = answers.filter((a, i) => a === questions[i]?.correctIndex).length;
  const pct = Math.round((score / questions.length) * 100);

  const grade =
    pct >= 80 ? { label: "Excellent", color: "#22c55e" }
    : pct >= 60 ? { label: "Good", color: styles.accent }
    : pct >= 40 ? { label: "Fair", color: "#f59e0b" }
    : { label: "Needs Review", color: "#ef4444" };

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        gap: "28px",
        animation: "cardIn 0.4s ease forwards",
      }}
    >
      <div
        style={{
          width: 100,
          height: 100,
          borderRadius: "50%",
          background: `${grade.color}18`,
          border: `2px solid ${grade.color}`,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          boxShadow: `0 0 0 8px ${grade.color}0e`,
        }}
      >
        <span
          style={{
            fontSize: "28px",
            fontWeight: "800",
            color: grade.color,
            lineHeight: 1,
          }}
        >
          {pct}%
        </span>
        <span style={{ fontSize: "10px", color: grade.color, fontWeight: "600" }}>
          {score}/{questions.length}
        </span>
      </div>

      <div style={{ textAlign: "center" }}>
        <p
          style={{
            fontSize: "22px",
            fontWeight: "800",
            color: "var(--color-text)",
            marginBottom: "8px",
            letterSpacing: "-0.02em",
          }}
        >
          {grade.label}
        </p>
        <p style={{ fontSize: "14px", color: "var(--color-subtext)", lineHeight: 1.6 }}>
          You answered {score} of {questions.length} questions correctly.
        </p>
      </div>

      {/* Per-question recap */}
      <div
        style={{
          width: "100%",
          display: "flex",
          flexDirection: "column",
          gap: "8px",
        }}
      >
        {questions.map((q, i) => {
          const correct = answers[i] === q.correctIndex;
          return (
            <div
              key={q.id}
              style={{
                display: "flex",
                alignItems: "flex-start",
                gap: "10px",
                padding: "10px 14px",
                borderRadius: "10px",
                border: "1px solid var(--color-border)",
                background: "var(--color-surface)",
              }}
            >
              {correct ? (
                <CheckCircle2 size={16} color="#22c55e" style={{ flexShrink: 0, marginTop: 2 }} />
              ) : (
                <XCircle size={16} color="#ef4444" style={{ flexShrink: 0, marginTop: 2 }} />
              )}
              <p style={{ fontSize: "13px", color: "var(--color-text)", lineHeight: 1.5 }}>
                {q.question}
              </p>
            </div>
          );
        })}
      </div>

      <div style={{ display: "flex", gap: "12px", width: "100%", flexWrap: "wrap" }}>
        <button
          onClick={onViewStats}
          style={{
            flex: 1,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "8px",
            padding: "13px 20px",
            borderRadius: "11px",
            border: "none",
            background: styles.accent,
            color: "#fff",
            cursor: "pointer",
            fontSize: "14px",
            fontWeight: "700",
            boxShadow: `0 4px 16px ${styles.accent}44`,
          }}
        >
          <BarChart3 size={15} />
          View Statistics
        </button>
        <button
          onClick={onRetry}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            padding: "13px 20px",
            borderRadius: "11px",
            border: "1px solid var(--color-border)",
            background: "var(--color-surface)",
            color: "var(--color-text)",
            cursor: "pointer",
            fontSize: "14px",
            fontWeight: "500",
          }}
        >
          <RefreshCw size={14} />
          Retry
        </button>
      </div>
    </div>
  );
}

// ─── Assessment page ──────────────────────────────────────────────────────────
export default function Assessment() {
  const navigate = useNavigate();
  const { styles, fontFamily } = useTheme();
  const { extractedText, documentTitle, addSessionResult } =
    useContext(ReaderContext);

  const [status, setStatus] = useState("idle"); // idle | loading | ready | error | complete
  const [questions, setQuestions] = useState([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState([]);
  const [errorMsg, setErrorMsg] = useState("");

  const isUsingFallback =
    OPENAI_API_KEY === "YOUR_OPENAI_API_KEY_HERE";

  const startQuiz = async () => {
    setStatus("loading");
    setAnswers([]);
    setCurrentIndex(0);

    try {
      if (isUsingFallback) {
        await new Promise((r) => setTimeout(r, 900));
        setQuestions(FALLBACK_QUIZ);
      } else {
        const quiz = await generateQuiz(extractedText || "");
        setQuestions(quiz);
      }
      setStatus("ready");
    } catch (err) {
      console.error("Quiz generation error:", err);
      setErrorMsg(err.message || "Failed to generate quiz.");
      setStatus("error");
    }
  };

  const handleAnswer = (optionIndex) => {
    if (answers[currentIndex] !== undefined) return;
    const next = [...answers];
    next[currentIndex] = optionIndex;
    setAnswers(next);
  };

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex((i) => i + 1);
    } else {
      // Save result to context
      const score = answers.filter(
        (a, i) => a === questions[i]?.correctIndex
      ).length;
      addSessionResult?.({
        date: new Date().toISOString(),
        score,
        total: questions.length,
        title: documentTitle || "Untitled",
      });
      setStatus("complete");
    }
  };

  const handleRetry = () => {
    setStatus("idle");
    setQuestions([]);
    setAnswers([]);
    setCurrentIndex(0);
  };

  return (
    <>
      <style>{`
        @keyframes cardIn {
          from { opacity: 0; transform: translateY(18px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        @keyframes fadeIn {
          from { opacity: 0; }
          to   { opacity: 1; }
        }
        @keyframes spin {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
      `}</style>

      <div
        style={{
          minHeight: "100vh",
          background: "var(--color-bg)",
          fontFamily,
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "center",
          padding: "48px 24px 80px",
        }}
      >
        <div style={{ width: "100%", maxWidth: "620px" }}>
          {/* Header */}
          <header style={{ marginBottom: "36px", animation: "cardIn 0.4s ease" }}>
            <p
              style={{
                fontSize: "11px",
                letterSpacing: "0.12em",
                textTransform: "uppercase",
                color: "var(--color-subtext)",
                fontWeight: "600",
                marginBottom: "8px",
              }}
            >
              Comprehension Check
            </p>
            <h1
              style={{
                fontSize: "26px",
                fontWeight: "800",
                color: "var(--color-text)",
                letterSpacing: "-0.02em",
                lineHeight: "1.2",
              }}
            >
              {documentTitle || "Reading Assessment"}
            </h1>
          </header>

          {/* Idle state */}
          {status === "idle" && (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "24px",
                padding: "48px 32px",
                background: "var(--color-surface)",
                border: "1px solid var(--color-border)",
                borderRadius: "16px",
                textAlign: "center",
                animation: "cardIn 0.4s ease",
              }}
            >
              <div
                style={{
                  width: 60,
                  height: 60,
                  borderRadius: "50%",
                  background: `${styles.accent}18`,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <Sparkles size={26} color={styles.accent} />
              </div>
              <div>
                <p
                  style={{
                    fontSize: "17px",
                    fontWeight: "700",
                    color: "var(--color-text)",
                    marginBottom: "8px",
                  }}
                >
                  Ready to test your comprehension?
                </p>
                <p
                  style={{
                    fontSize: "13px",
                    color: "var(--color-subtext)",
                    lineHeight: 1.6,
                  }}
                >
                  {isUsingFallback
                    ? "5 sample questions will be generated. Add your OpenAI API key to generate questions from your own PDF."
                    : "Claude will generate 5 multiple-choice questions based on your PDF."}
                </p>
              </div>
              <button
                onClick={startQuiz}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                  padding: "13px 28px",
                  borderRadius: "11px",
                  border: "none",
                  background: styles.accent,
                  color: "#fff",
                  cursor: "pointer",
                  fontSize: "14px",
                  fontWeight: "700",
                  boxShadow: `0 4px 16px ${styles.accent}44`,
                }}
              >
                <Sparkles size={15} />
                Generate Quiz
              </button>
            </div>
          )}

          {/* Loading */}
          {status === "loading" && (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "16px",
                padding: "64px 32px",
                background: "var(--color-surface)",
                border: "1px solid var(--color-border)",
                borderRadius: "16px",
                textAlign: "center",
                animation: "cardIn 0.3s ease",
              }}
            >
              <Loader2
                size={32}
                color={styles.accent}
                style={{ animation: "spin 0.9s linear infinite" }}
              />
              <p style={{ fontSize: "15px", color: "var(--color-subtext)" }}>
                Generating your quiz…
              </p>
            </div>
          )}

          {/* Error */}
          {status === "error" && (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "16px",
                padding: "48px 32px",
                background: "#ef444408",
                border: "1px solid #ef444433",
                borderRadius: "16px",
                textAlign: "center",
                animation: "cardIn 0.3s ease",
              }}
            >
              <AlertCircle size={28} color="#ef4444" />
              <div>
                <p style={{ fontSize: "15px", fontWeight: "600", color: "#dc2626", marginBottom: "6px" }}>
                  Failed to generate quiz
                </p>
                <p style={{ fontSize: "13px", color: "var(--color-subtext)" }}>{errorMsg}</p>
              </div>
              <button
                onClick={handleRetry}
                style={{
                  padding: "10px 22px",
                  borderRadius: "10px",
                  border: "1px solid var(--color-border)",
                  background: "var(--color-surface)",
                  color: "var(--color-text)",
                  cursor: "pointer",
                  fontSize: "13px",
                  fontWeight: "600",
                }}
              >
                Try Again
              </button>
            </div>
          )}

          {/* Active quiz */}
          {status === "ready" && questions.length > 0 && (
            <QuizCard
              key={currentIndex}
              question={questions[currentIndex]}
              qIndex={currentIndex}
              total={questions.length}
              answer={answers[currentIndex]}
              onAnswer={handleAnswer}
              onNext={handleNext}
              isLast={currentIndex === questions.length - 1}
              styles={styles}
            />
          )}

          {/* Results */}
          {status === "complete" && (
            <ResultsScreen
              questions={questions}
              answers={answers}
              onRetry={handleRetry}
              onViewStats={() => navigate("/profile")}
              styles={styles}
            />
          )}
        </div>
      </div>
    </>
  );
}