import React, { useRef, useState, useEffect, useContext } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Sparkles,
  Type,
  Volume2,
  Sun,
  Moon,
  BookOpen,
  ClipboardList,
  RotateCcw,
  BookMarked,
  ChevronUp,
  ChevronDown,
  Book,
} from "lucide-react";

import { useTheme, THEMES } from "../context/ThemeContext";
import { ReaderContext } from "../context/ReaderContext";
import useLineParser from "../hooks/useLineParser";
import useReaderNavigation from "../hooks/useReaderNavigation";
import PomodoroTimer from "../components/reader/PomodoroTimer";
import DictionaryPanel from "../components/reader/DictionaryPanel";

// ─── Sample text ──────────────────────────────────────────────────────────────
const SAMPLE_TEXT = `Cognitive load theory, developed by John Sweller in the late 1980s,
is a framework that describes how the human brain processes and stores information during
learning. The theory posits that working memory, the cognitive system responsible for
temporarily holding and manipulating information, has a strictly limited capacity. When
instructional material overwhelms this capacity, learning becomes inefficient or fails
entirely. Sweller identified three distinct types of cognitive load that operate
simultaneously during any learning episode. Intrinsic load refers to the inherent
complexity of the subject matter itself and the degree to which its elements interact
with one another. Extraneous load is generated by the design of instructional materials
and does not contribute to learning; it is imposed by poor presentation, unnecessary
decorative elements, or redundant information. Germane load, the most valuable of the
three, is the mental effort dedicated to constructing and automating schemas, which are
organized knowledge structures stored in long-term memory. Effective instructional design
seeks to reduce extraneous load as much as possible, manage intrinsic load through
sequencing and scaffolding, and redirect freed cognitive resources toward germane
processing. Research in this domain has produced a number of empirically validated
principles, including the worked example effect, the split-attention effect, the
redundancy effect, and the expertise reversal effect. These findings have profound
implications for educators, interface designers, and anyone tasked with communicating
complex information to a human audience.`;

// ─── Line highlight helper (uses inline styles for dynamic colors) ─────────────
function getLineStyle(lineIndex, activeIndex, theme) {
  const isDark = theme === THEMES.DARK;

  if (lineIndex === activeIndex) {
    return {
      background: isDark ? "#1f2937" : "#354024",
      color: "#ffffff",
      borderRadius: "10px",
      transform: "scale(1.01)",
      boxShadow: "0 4px 18px rgba(0, 0, 0, 0.28)",
      opacity: 1,
    };
  }

  if (lineIndex === activeIndex - 1 || lineIndex === activeIndex + 1) {
    return {
      background: isDark ? "#374151" : "#747a67",
      color: isDark ? "#e5e5e5" : "#000000",
      borderRadius: "10px",
      opacity: 0.75,
    };
  }

  return {
    background: "transparent",
    color: "inherit", 
    opacity: 0.25,
  };
}

// ─── Sidebar toggle button ────────────────────────────────────────────────────
function SidebarToggle({ icon, label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={[
        "flex items-center gap-3 w-full px-4 py-3 rounded-2xl text-sm font-semibold",
        "border transition-all duration-200 text-left",
        active
          ? "bg-[#3d3c22] text-white border-[#3d3c22] shadow-md shadow-black"
          : "bg-[#605e34] text-white border-[#605e34] hover:border-[#3d3c22] hover:text-white",
      ].join(" ")}
    >
      <span className={active ? "text-white" : "text-white"}>{icon}</span>
      {label}
      {/* Pill indicator */}
      <span
        className={[
          "ml-auto w-8 h-4 rounded-full flex items-center px-0.5 transition-all duration-300",
          active ? "bg-white/30 justify-end" : "bg-[#c8bea5] justify-start",
        ].join(" ")}
      >
        <span
          className={[
            "w-3 h-3 rounded-full transition-all duration-300",
            active ? "bg-white" : "bg-white",
          ].join(" ")}
        />
      </span>
    </button>
  );
}

// ─── Sprite ───────────────────────────────────────────────────────────────────
function Sprite() {
  return (
    <div className="flex justify-center">
      <img
        src="/images/read-mascot.png"
        alt="sprite"
        className="w-64 drop-shadow-[0_25px_40px_rgba(0,0,0,0.45)]"
      />
    </div>
  );
}

// ─── Completion banner ────────────────────────────────────────────────────────
function CompletionBanner({ onAssessment, onRestart }) {
  return (
    <div className="mt-10 bg-[#9d9167] border border-[#9d9167] rounded-3xl p-8 flex flex-col items-center gap-5 shadow-lg shadow-[#3d3c22] animate-[fadeSlideUp_0.5s_ease_forwards]">
      <div className="w-14 h-14 rounded-full bg-[#3d3c22] border-2 border-[#3d3c22] flex items-center justify-center">
        <BookMarked size={24} className="text-white" />
      </div>
      <div className="text-center">
        <p className="text-lg font-bold text-[white] mb-1">You've reached the end!</p>
        <p className="text-sm text-[#fff8df] max-w-xs leading-relaxed">
          Excellent focus session. Ready to test your comprehension?
        </p>
      </div>
      <div className="flex gap-3 flex-wrap justify-center w-full">
        <button
          onClick={onAssessment}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-[#605e34] hover:bg-[#3d3c22] active:scale-95 text-white text-sm font-bold shadow-lg shadow-[#3d3c22] transition-all duration-150"
        >
          <ClipboardList size={15} />
          Take Reading Assessment
        </button>
        <button
          onClick={onRestart}
          className="flex items-center gap-2 px-5 py-3 rounded-full bg-white border border-[white] hover:border-[#3d3c22] text-slate-600 hover:text-slate-600 text-sm font-medium transition-all duration-150"
        >
          <RotateCcw size={14} />
          Back to Start
        </button>
      </div>
    </div>
  );
}

// ─── Nav hint bar ─────────────────────────────────────────────────────────────
function NavHint({ onNext, onPrev, activeIndex, total }) {
  return (
    <div className="flex items-center justify-between mt-6 px-4 py-3 rounded-2xl bg-[#d1c394] border border-[#c8bea5]">
      <button
        onClick={onPrev}
        disabled={activeIndex === 0}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-[#605e34] hover:text-[black] disabled:opacity-30 disabled:cursor-not-allowed transition-colors duration-150"
      >
        <ChevronUp size={13} /> Prev
      </button>
      <span className="text-[11px] text-white font-medium">
        Line {activeIndex + 1} of {total} · <kbd className="font-semibold text-[#747a67]">Space</kbd> or <kbd className="font-semibold text-[#747a67]">↓</kbd> to advance
      </span>
      <button
        onClick={onNext}
        disabled={activeIndex >= total - 1}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-[#605e34] hover:text-[black] disabled:opacity-30 disabled:cursor-not-allowed transition-colors duration-150"
      >
        Next <ChevronDown size={13} />
      </button>
    </div>
  );
}

// ─── Main Read Page ───────────────────────────────────────────────────────────
export default function Read() {
  const navigate = useNavigate();
  const { font, toggleFont, FONTS: FONT_OPTIONS, cycleTheme, theme } =
    useTheme();
  const { extractedText, documentTitle } = useContext(ReaderContext);

  // ── STATE & LOGIC: UNCHANGED ───────────────────────────────────────────────
  const [audioEnabled, setAudioEnabled] = useState(false);
  const [isDictionaryOpen, setIsDictionaryOpen] = useState(false);

  const trimmedExtracted = (extractedText || "").trim();
  const textToRender =
    trimmedExtracted.length > 0 ? trimmedExtracted : SAMPLE_TEXT;
  const { containerRef, lines, isReady, reparse } = useLineParser(textToRender);

  const readingAreaRef = useRef(null);
  const { activeLineIndex, goToNext, goToPrev, reset, isComplete } =
    useReaderNavigation(lines.length, isReady, readingAreaRef);

  const lineRefs = useRef([]);
  useEffect(() => {
    const el = lineRefs.current[activeLineIndex];
    if (el) el.scrollIntoView({ block: "center", behavior: "smooth" });
  }, [activeLineIndex]);

  useEffect(() => {
    let timeout;
    const onResize = () => { clearTimeout(timeout); timeout = setTimeout(reparse, 200); };
    window.addEventListener("resize", onResize);
    return () => { window.removeEventListener("resize", onResize); clearTimeout(timeout); };
  }, [reparse]);

  useEffect(() => {
    if (!audioEnabled) {
      window.speechSynthesis.cancel();
    }
  }, [audioEnabled]);

  useEffect(() => {
    if (!audioEnabled || !isReady || lines.length === 0) return;
    const line = lines[activeLineIndex];
    const text = line?.text?.trim();
    if (!text) return;
    window.speechSynthesis.cancel();
    const utter = new SpeechSynthesisUtterance(text);
    utter.rate = 0.95;
    window.speechSynthesis.speak(utter);
    return () => {
      window.speechSynthesis.cancel();
    };
  }, [audioEnabled, activeLineIndex, isReady, lines]);
  // ── END LOGIC ──────────────────────────────────────────────────────────────

  const progressPct = lines.length > 1
    ? Math.round((activeLineIndex / (lines.length - 1)) * 100)
    : 0;

  const isOD = font === FONT_OPTIONS.OPEN_DYSLEXIC;

  const themeModeIcon =
    theme === THEMES.DARK ? (
      <Moon size={14} />
    ) : theme === THEMES.READING ? (
      <BookOpen size={14} />
    ) : (
      <Sun size={14} />
    );
  const themeLabel =
    theme === THEMES.DARK
      ? "Dark"
      : theme === THEMES.READING
        ? "Reading"
        : "Light";

  const handleAudioToggle = () => {
    setAudioEnabled((v) => {
      const next = !v;
      if (!next) window.speechSynthesis.cancel();
      return next;
    });
  };

const paperStyles =
  theme === THEMES.DARK
    ? {
        backgroundColor: "#1a1a1a",
        color: "#e5e5e5",
      }
    : theme === THEMES.READING
    ? {
        backgroundColor: "#fff2dc", // warm paper
        color: "#3d3c22",
      }
    : {
        backgroundColor: "#ffffff",
        color: "#1f2937",
      };

const overlayStyle =
  theme === THEMES.DARK
    ? {
        backgroundColor: "rgba(0, 0, 0, 0.55)", // dim whole UI
      }
    : theme === THEMES.READING
    ? {
        backgroundColor: "rgba(255, 244, 214, 0.35)", // warm tone
      }
    : {
        backgroundColor: "transparent",
      };

  return (
    <>
      <style>{`
        @keyframes fadeSlideUp {
          from { opacity: 0; transform: translateY(20px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .read-line {
          transition: background 0.3s ease, color 0.3s ease,
                      opacity 0.3s ease, transform 0.25s ease,
                      box-shadow 0.3s ease;
        }
      `}</style>

      {/* ── Full page shell ─────────────────────────────────────────────── */}
      <div
  className="relative flex h-screen overflow-hidden"
  style={{
    backgroundImage: "url('/images/bg.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
  }}
>
  {/* THEME OVERLAY */}
  <div
    className="absolute inset-0 pointer-events-none z-0 transition-all duration-300"
    style={overlayStyle}
  />

  {/* CONTENT WRAPPER */}
  <div className="relative z-10 flex w-full">

        {/* ── Green progress bar — fixed across very top ─────────────────── */}
        <div className="fixed top-0 left-0 right-0 h-1 bg-green-100 z-50">
          <div
            className="h-full bg-green-500 rounded-full transition-all duration-500 ease-out"
            style={{ width: `${progressPct}%` }}
            role="progressbar"
            aria-valuenow={progressPct}
            aria-valuemin={0}
            aria-valuemax={100}
          />
        </div>

        {/* ── LEFT SIDEBAR ────────────────────────────────────────────────── */}
        <aside
          className="w-64 flex-shrink-0 flex flex-col bg-[#9d9167]/90 backdrop-blur-md rounded-r-3xl px-5 py-6 gap-5 overflow-y-auto shadow-[8px_0_25px_rgba(0,0,0,0.25)]"
          aria-label="Reading controls"
        >
          {/* Back arrow */}
          <button
            onClick={() => navigate("/")}
            aria-label="Back to home"
            className="w-9 h-9 flex items-center justify-center rounded-full bg-[#615e3a] border border-[#615e3a] text-[#9d9167] hover:bg-[#615e3a] hover:text-[#c8bea5] hover:border-[#615e3a] shadow-sm transition-all duration-200 self-start"
          >
            <ArrowLeft size={16} />
          </button>

          {/* Sprite */}
          <Sprite />

          {/* Divider */}
          <div className="h-px bg-[#625528] mx-1" />

          {/* Toggle buttons */}
          <div className="flex flex-col gap-2">
            <SidebarToggle
              icon={<Type size={14} />}
              label="OpenDyslexic"
              active={isOD}
              onClick={toggleFont}
            />
            <SidebarToggle
              icon={<Volume2 size={14} />}
              label="Audio Option"
              active={audioEnabled}
              onClick={handleAudioToggle}
            />
            <SidebarToggle
              icon={<Book size={14} />}
              label="Dictionary"
              active={isDictionaryOpen}
              onClick={() => setIsDictionaryOpen((v) => !v)}
            />
            <SidebarToggle
              icon={themeModeIcon}
              label={themeLabel}
              active={theme !== THEMES.LIGHT}
              onClick={cycleTheme}
            />
          </div>

          {/* Pomodoro — pinned to bottom */}
          <div className="mt-auto">
            <PomodoroTimer />
          </div>
        </aside>

        {/* ── MAIN CONTENT AREA ───────────────────────────────────────────── */}
        <main
          ref={readingAreaRef}
          className="flex-1 overflow-y-auto pt-7 pb-16 px-6 flex flex-col items-center"
          tabIndex={-1}
          aria-label="Reading content"
        >
          {/* Hidden measuring container — needed by useLineParser */}
          <div
            ref={containerRef}
            aria-hidden="true"
            className="absolute invisible pointer-events-none text-lg leading-loose"
            style={{
              // Match visible text width: card max (48rem) minus card px-10 and line px-3
              width:
                "calc(min(48rem, 100vw - 14rem - 3rem) - 5rem - 1.5rem)",
              fontFamily: isOD ? "'OpenDyslexic', sans-serif" : "inherit",
              whiteSpace: "normal",
              wordBreak: "break-word",
            }}
          />

          {/* ── Document "paper" card ───────────────────────────────────── */}
          <div
            className="w-full max-w-3xl rounded-3xl shadow-2xl shadow-black px-10 pt-9 pb-10"
            style={{
              ...paperStyles,
              fontFamily: isOD ? "'OpenDyslexic', sans-serif" : "'Georgia', serif",
            }}
          >
            {/* Document header */}
            <header className="mb-6 border-b border-black pb-5">
              <p className="text-[10px] font-extrabold tracking-[0.16em] uppercase mb-1.5 opacity-70">
                Academic Reading
              </p>
              <h1 className="text-2xl font-bold leading-tight tracking-tight">
                {documentTitle || "bookO"}
              </h1>

              {/* Progress bar inside card */}
              {isReady && lines.length > 0 && (
                <div className="flex items-center gap-3 mt-4">
                  <div className="flex-1 h-1.5 border border-[#9d9167] rounded-full overflow-hidden bg-transparent">
                    <div
                      className="h-full bg-[#354024] rounded-full transition-all duration-500 ease-out"
                      style={{ width: `${progressPct}%` }}
                    />
                  </div>
                  <span className="text-[11px] font-bold tabular-nums min-w-[32px] text-right opacity-80">
                    {progressPct}%
                  </span>
                </div>
              )}
            </header>

            {/* Skeleton while parsing */}
            {!isReady && (
              <div className="flex flex-col gap-3 animate-pulse">
                {[...Array(7)].map((_, i) => (
                  <div
                    key={i}
                    className="h-5 bg-black rounded-lg"
                    style={{ width: i % 3 === 2 ? "55%" : "100%" }}
                  />
                ))}
              </div>
            )}

            {/* Rendered lines */}
            {isReady && (
              <div role="article" className="flex flex-col gap-0.5">
                {lines.map((line, i) => (
                  <div
                    key={i}
                    ref={(el) => (lineRefs.current[i] = el)}
                    className="read-line text-[17px] leading-loose px-3 py-1 cursor-default text-justify"
                    style={getLineStyle(i, activeLineIndex, theme)}
                    role="paragraph"
                    aria-current={i === activeLineIndex ? "true" : undefined}
                    onClick={() => {
                      if (i === activeLineIndex + 1) goToNext();
                      if (i === activeLineIndex - 1) goToPrev();
                    textAlign: "justify"
                    }}
                  >
                    {line.text}
                  </div>
                ))}
              </div>
            )}

            {/* Completion banner */}
            {isReady && isComplete && lines.length > 0 && (
              <CompletionBanner
                onAssessment={() => navigate("/assessment")}
                onRestart={reset}
              />
            )}

            {/* Nav hint */}
            {isReady && lines.length > 0 && !isComplete && (
              <NavHint
                onNext={goToNext}
                onPrev={goToPrev}
                activeIndex={activeLineIndex}
                total={lines.length}
              />
            )}
          </div>
        </main>

        {isDictionaryOpen && (
          <DictionaryPanel onClose={() => setIsDictionaryOpen(false)} />
        )}
      </div>
      </div>
    </>
  );
}