import React, { useRef, useState, useEffect, useContext } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Sparkles,
  Type,
  Volume2,
  Sun,
  ClipboardList,
  RotateCcw,
  BookMarked,
  ChevronUp,
  ChevronDown,
} from "lucide-react";

import { useTheme, FONTS } from "../context/ThemeContext";
import { ReaderContext } from "../context/ReaderContext";
import useLineParser from "../hooks/useLineParser";
import useReaderNavigation from "../hooks/useReaderNavigation";
import PomodoroTimer from "../components/reader/PomodoroTimer";

// ─── Sample text ──────────────────────────────────────────────────────────────
const SAMPLE_TEXT = `Cognitive load theory, developed by John Sweller in the late 1980s,
is a framework that describes how the human brain processes and stores information during
learning. The theory posits that working memory, the cognitive system responsible for
temporarily holding and manipulating information, has a strictly limited capacity. When
instructional material overwhelms this capacity, learning becomes inefficient or fails
entirely. Sweller identified three distinct types of cognitive load that operate
simultaneously during any learning episode. Intrinsic load refers to the inherent
complexity of the subject matter itself and the degree to which its elements interact
with one another. Extraneous load is generated by the design of instructional materials
and does not contribute to learning; it is imposed by poor presentation, unnecessary
decorative elements, or redundant information. Germane load, the most valuable of the
three, is the mental effort dedicated to constructing and automating schemas, which are
organized knowledge structures stored in long-term memory. Effective instructional design
seeks to reduce extraneous load as much as possible, manage intrinsic load through
sequencing and scaffolding, and redirect freed cognitive resources toward germane
processing. Research in this domain has produced a number of empirically validated
principles, including the worked example effect, the split-attention effect, the
redundancy effect, and the expertise reversal effect. These findings have profound
implications for educators, interface designers, and anyone tasked with communicating
complex information to a human audience.`;

// ─── Line highlight helper (uses inline styles for dynamic colors) ─────────────
function getLineStyle(lineIndex, activeIndex) {
  if (lineIndex === activeIndex) {
    return {
      background: "#f97316",       // orange-500
      color: "#ffffff",
      borderRadius: "10px",
      transform: "scale(1.01)",
      boxShadow: "0 4px 18px rgba(249,115,22,0.28)",
      opacity: 1,
    };
  }
  if (lineIndex === activeIndex - 1 || lineIndex === activeIndex + 1) {
    return {
      background: "#fed7aa",       // orange-200
      color: "#7c2d12",            // orange-950
      borderRadius: "10px",
      transform: "scale(1)",
      opacity: 0.75,
    };
  }
  return {
    background: "transparent",
    color: "#374151",              // gray-700
    opacity: 0.25,
    borderRadius: "10px",
    transform: "scale(1)",
  };
}

// ─── Sidebar toggle button ────────────────────────────────────────────────────
function SidebarToggle({ icon, label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={[
        "flex items-center gap-3 w-full px-4 py-3 rounded-2xl text-sm font-semibold",
        "border transition-all duration-200 text-left",
        active
          ? "bg-orange-400 text-white border-orange-400 shadow-md shadow-orange-200"
          : "bg-white text-slate-600 border-orange-100 hover:border-orange-300 hover:text-orange-500",
      ].join(" ")}
    >
      <span className={active ? "text-white" : "text-orange-400"}>{icon}</span>
      {label}
      {/* Pill indicator */}
      <span
        className={[
          "ml-auto w-8 h-4 rounded-full flex items-center px-0.5 transition-all duration-300",
          active ? "bg-white/30 justify-end" : "bg-orange-100 justify-start",
        ].join(" ")}
      >
        <span
          className={[
            "w-3 h-3 rounded-full transition-all duration-300",
            active ? "bg-white" : "bg-orange-300",
          ].join(" ")}
        />
      </span>
    </button>
  );
}

// ─── Sprite ───────────────────────────────────────────────────────────────────
function Sprite() {
  return (
    <div className="flex flex-col items-center gap-1 py-2">
      <div className="relative w-20 h-20">
        {/* Outer glow ring */}
        <div className="absolute inset-0 rounded-full bg-orange-200 animate-ping opacity-20" />
        {/* Main circle */}
        <div className="relative w-20 h-20 rounded-full bg-gradient-to-br from-orange-300 to-amber-400 flex flex-col items-center justify-center shadow-lg shadow-orange-300/40 border-2 border-orange-200">
          <Sparkles size={22} className="text-white drop-shadow" />
          <span className="text-[9px] font-black tracking-[0.18em] uppercase text-white/90 mt-0.5">
            Sprite
          </span>
        </div>
      </div>
    </div>
  );
}

// ─── Completion banner ────────────────────────────────────────────────────────
function CompletionBanner({ onAssessment, onRestart }) {
  return (
    <div className="mt-10 bg-orange-50 border border-orange-200 rounded-3xl p-8 flex flex-col items-center gap-5 shadow-lg shadow-orange-100 animate-[fadeSlideUp_0.5s_ease_forwards]">
      <div className="w-14 h-14 rounded-full bg-orange-100 border-2 border-orange-300 flex items-center justify-center">
        <BookMarked size={24} className="text-orange-500" />
      </div>
      <div className="text-center">
        <p className="text-lg font-bold text-slate-800 mb-1">You've reached the end!</p>
        <p className="text-sm text-slate-500 max-w-xs leading-relaxed">
          Excellent focus session. Ready to test your comprehension?
        </p>
      </div>
      <div className="flex gap-3 flex-wrap justify-center w-full">
        <button
          onClick={onAssessment}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-orange-400 hover:bg-orange-500 active:scale-95 text-white text-sm font-bold shadow-lg shadow-orange-200 transition-all duration-150"
        >
          <ClipboardList size={15} />
          Take Reading Assessment
        </button>
        <button
          onClick={onRestart}
          className="flex items-center gap-2 px-5 py-3 rounded-full bg-white border border-orange-200 hover:border-orange-400 text-slate-600 hover:text-orange-500 text-sm font-medium transition-all duration-150"
        >
          <RotateCcw size={14} />
          Back to Start
        </button>
      </div>
    </div>
  );
}

// ─── Nav hint bar ─────────────────────────────────────────────────────────────
function NavHint({ onNext, onPrev, activeIndex, total }) {
  return (
    <div className="flex items-center justify-between mt-6 px-4 py-3 rounded-2xl bg-orange-50 border border-orange-100">
      <button
        onClick={onPrev}
        disabled={activeIndex === 0}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-500 hover:text-orange-500 disabled:opacity-30 disabled:cursor-not-allowed transition-colors duration-150"
      >
        <ChevronUp size={13} /> Prev
      </button>
      <span className="text-[11px] text-slate-400 font-medium">
        Line {activeIndex + 1} of {total} · <kbd className="font-semibold text-orange-400">Space</kbd> or <kbd className="font-semibold text-orange-400">↓</kbd> to advance
      </span>
      <button
        onClick={onNext}
        disabled={activeIndex >= total - 1}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-slate-500 hover:text-orange-500 disabled:opacity-30 disabled:cursor-not-allowed transition-colors duration-150"
      >
        Next <ChevronDown size={13} />
      </button>
    </div>
  );
}

// ─── Main Read Page ───────────────────────────────────────────────────────────
export default function Read() {
  const navigate = useNavigate();
  const { font, toggleFont, FONTS: FONT_OPTIONS } = useTheme();
  const { extractedText, documentTitle } = useContext(ReaderContext);

  // ── STATE & LOGIC: UNCHANGED ───────────────────────────────────────────────
  const [audioEnabled, setAudioEnabled] = useState(false);
  const [modesEnabled, setModesEnabled] = useState(false);

  const textToRender = extractedText || SAMPLE_TEXT;
  const { containerRef, lines, isReady, reparse } = useLineParser(textToRender);

  const readingAreaRef = useRef(null);
  const { activeLineIndex, goToNext, goToPrev, reset, isComplete } =
    useReaderNavigation(lines.length, isReady, readingAreaRef);

  const lineRefs = useRef([]);
  useEffect(() => {
    const el = lineRefs.current[activeLineIndex];
    if (el) el.scrollIntoView({ block: "center", behavior: "smooth" });
  }, [activeLineIndex]);

  useEffect(() => {
    let timeout;
    const onResize = () => { clearTimeout(timeout); timeout = setTimeout(reparse, 200); };
    window.addEventListener("resize", onResize);
    return () => { window.removeEventListener("resize", onResize); clearTimeout(timeout); };
  }, [reparse]);
  // ── END LOGIC ──────────────────────────────────────────────────────────────

  const progressPct = lines.length > 1
    ? Math.round((activeLineIndex / (lines.length - 1)) * 100)
    : 0;

  const isOD = font === FONT_OPTIONS.OPEN_DYSLEXIC;

  return (
    <>
      <style>{`
        @keyframes fadeSlideUp {
          from { opacity: 0; transform: translateY(20px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .read-line {
          transition: background 0.3s ease, color 0.3s ease,
                      opacity 0.3s ease, transform 0.25s ease,
                      box-shadow 0.3s ease;
        }
      `}</style>

      {/* ── Full page shell ─────────────────────────────────────────────── */}
      <div className="flex h-screen overflow-hidden bg-orange-50/60">

        {/* ── Green progress bar — fixed across very top ─────────────────── */}
        <div className="fixed top-0 left-0 right-0 h-1 bg-green-100 z-50">
          <div
            className="h-full bg-green-500 rounded-full transition-all duration-500 ease-out"
            style={{ width: `${progressPct}%` }}
            role="progressbar"
            aria-valuenow={progressPct}
            aria-valuemin={0}
            aria-valuemax={100}
          />
        </div>

        {/* ── LEFT SIDEBAR ────────────────────────────────────────────────── */}
        <aside
          className="w-56 flex-shrink-0 flex flex-col bg-amber-100/70 border-r border-orange-200/60 px-4 py-6 gap-5 overflow-y-auto pt-5"
          aria-label="Reading controls"
        >
          {/* Back arrow */}
          <button
            onClick={() => navigate("/")}
            aria-label="Back to home"
            className="w-9 h-9 flex items-center justify-center rounded-full bg-white border border-orange-200 text-orange-400 hover:bg-orange-400 hover:text-white hover:border-orange-400 shadow-sm transition-all duration-200 self-start"
          >
            <ArrowLeft size={16} />
          </button>

          {/* Sprite */}
          <Sprite />

          {/* Divider */}
          <div className="h-px bg-orange-200/60 mx-1" />

          {/* Toggle buttons */}
          <div className="flex flex-col gap-2">
            <SidebarToggle
              icon={<Type size={14} />}
              label="OpenDyslexic"
              active={isOD}
              onClick={toggleFont}
            />
            <SidebarToggle
              icon={<Volume2 size={14} />}
              label="Audio Option"
              active={audioEnabled}
              onClick={() => setAudioEnabled((v) => !v)}
            />
            <SidebarToggle
              icon={<Sun size={14} />}
              label="Modes"
              active={modesEnabled}
              onClick={() => setModesEnabled((v) => !v)}
            />
          </div>

          {/* Pomodoro — pinned to bottom */}
          <div className="mt-auto">
            <PomodoroTimer />
          </div>
        </aside>

        {/* ── MAIN CONTENT AREA ───────────────────────────────────────────── */}
        <main
          ref={readingAreaRef}
          className="flex-1 overflow-y-auto pt-7 pb-16 px-6 flex flex-col items-center"
          tabIndex={-1}
          aria-label="Reading content"
        >
          {/* Hidden measuring container — needed by useLineParser */}
          <div
            ref={containerRef}
            aria-hidden="true"
            className="absolute invisible pointer-events-none text-lg leading-loose"
            style={{
              width: "min(680px, calc(100vw - 224px - 48px))",
              fontFamily: isOD ? "'OpenDyslexic', sans-serif" : "inherit",
              whiteSpace: "normal",
              wordBreak: "break-word",
            }}
          />

          {/* ── Document "paper" card ───────────────────────────────────── */}
          <div
            className="w-full max-w-2xl bg-white rounded-3xl shadow-2xl shadow-orange-100/80 px-10 pt-9 pb-10"
            style={{
              fontFamily: isOD ? "'OpenDyslexic', sans-serif" : "'Georgia', serif",
            }}
          >
            {/* Document header */}
            <header className="mb-6 border-b border-orange-100 pb-5">
              <p className="text-[10px] font-extrabold tracking-[0.16em] uppercase text-orange-300 mb-1.5">
                Academic Reading
              </p>
              <h1 className="text-2xl font-bold text-slate-800 leading-tight tracking-tight">
                {documentTitle || "bookO"}
              </h1>

              {/* Progress bar inside card */}
              {isReady && lines.length > 0 && (
                <div className="flex items-center gap-3 mt-4">
                  <div className="flex-1 h-1.5 bg-orange-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-orange-400 rounded-full transition-all duration-500 ease-out"
                      style={{ width: `${progressPct}%` }}
                    />
                  </div>
                  <span className="text-[11px] text-orange-400 font-bold tabular-nums min-w-[32px] text-right">
                    {progressPct}%
                  </span>
                </div>
              )}
            </header>

            {/* Skeleton while parsing */}
            {!isReady && (
              <div className="flex flex-col gap-3 animate-pulse">
                {[...Array(7)].map((_, i) => (
                  <div
                    key={i}
                    className="h-5 bg-orange-50 rounded-lg"
                    style={{ width: i % 3 === 2 ? "55%" : "100%" }}
                  />
                ))}
              </div>
            )}

            {/* Rendered lines */}
            {isReady && (
              <div role="article" className="flex flex-col gap-0.5">
                {lines.map((line, i) => (
                  <div
                    key={i}
                    ref={(el) => (lineRefs.current[i] = el)}
                    className="read-line text-[17px] leading-loose px-3 py-1 cursor-default"
                    style={getLineStyle(i, activeLineIndex)}
                    role="paragraph"
                    aria-current={i === activeLineIndex ? "true" : undefined}
                    onClick={() => {
                      if (i === activeLineIndex + 1) goToNext();
                      if (i === activeLineIndex - 1) goToPrev();
                    }}
                  >
                    {line.text}
                  </div>
                ))}
              </div>
            )}

            {/* Completion banner */}
            {isReady && isComplete && lines.length > 0 && (
              <CompletionBanner
                onAssessment={() => navigate("/assessment")}
                onRestart={reset}
              />
            )}

            {/* Nav hint */}
            {isReady && lines.length > 0 && !isComplete && (
              <NavHint
                onNext={goToNext}
                onPrev={goToPrev}
                activeIndex={activeLineIndex}
                total={lines.length}
              />
            )}
          </div>
        </main>
      </div>
    </>
  );
}